.PHONY: migrate makemigrations runserver test shell

migrate:
	uv run python manage.py migrate

makemigrations:
	uv run python manage.py makemigrations

runserver:
	uv run python manage.py runserver

test:
	uv run pytest

shell:
	uv run python manage.py shell
